server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth_server?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      show_sql: true
      format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
